#! /bin/bash

echo Welcome To Deepin Linux Kernel Build
echo Thanks @fslong Config
echo 安装依赖...
sudo apt install git wget fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison zstd debhelper
echo 下载-解压源码包...
wget https://mirrors.tuna.tsinghua.edu.cn/kernel/v6.x/linux-6.6.6.tar.xz
tar -xf linux-6.6.6.tar.xz
echo Copying Config...
cp amd64-desktop-zhsoft-deepin.config linux-6.6.6/.config
cd linux-6.6.6
echo 配置...
make menuconfig
echo 开始编译....
make -j32
echo Build DEB...
make bindeb-pkg
echo All Done...
cd ..
ls
